[build]
buildCommand = "NODE_ENV=production pnpm install && node scripts/update-metadata.js && pnpm --filter @meetup/shared build && pnpm --filter ./server build && pnpm --filter ./client build"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
