[build]
buildCommand = "NODE_ENV=production pnpm install && pnpm --filter @meetup/shared build && pnpm --filter ./server build && pnpm --filter ./client build"

[deploy]
startCommand = "NODE_ENV=production node server/dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
